sprint 2 increments
AtCliffUnderline/url-shortener pull request #4
Opened 2022-03-07 19:24 UTC by AtCliffUnderline

2022-03-08 10:18 UTC, AtCliffUnderline commented on internal/app/config.go
> +	}
костыли костылечки. А как лучше мержить конфиги?

2022-03-09 23:50 UTC, blattaria7 commented on internal/app/config.go
> +	}
как вариант, можно сначала парсить данные из конфига(в main), а потом смотреть флаги, и если они ненулевые, то они обновятся)

2022-03-09 23:54 UTC, blattaria7 commented on cmd/shortener/main.go
> +func init() {
Этот метод нигде не вызывается?

2022-03-10 00:05 UTC, blattaria7 commented on internal/app/storage.go
> +func (DefaultRouteStorage) ShortRoute(fullRoute string) (int, error) {
функция возвращает ошибку, но мы ее нигде не воспроизводим в этом методе. надо либо что-то обработать, либо убрать ее из возвращаемых аргументов)

2022-03-10 00:42 UTC, blattaria7 commented on internal/app/storage.go
>  func (DefaultRouteStorage) GetRouteByID(id int) (string, error) {
лучше разделить реализацию данных стораджей по разным файлам (это для читаемости 🤓 и удобства тестирования - отдельная сущность в отдельном пространстве)

2022-03-10 00:43 UTC, blattaria7 commented on internal/app/storage.go
> +			panic(err)
паники лучше не использовать - это ну очень радикальный способ все остановить ) часто в примерах их используют, но по опыту скажу - лучше стараться их избегать и просто возвращать ошибку здесь

2022-03-10 00:47 UTC, blattaria7 requested changes
Пока не могу поставить аппрув, к сожалению, так как нужна будет доработка, требующая моего повторного ревью (с конфигами) :( 
Остальные комментарии кажется, что небольшие и не отнимут много времени, но если будут вопросы - пиши, ставь 1-1)

2022-03-14 21:54 UTC, blattaria7 approved these changes
Все супер, ставлю аппрув)

Как будет возможность, проверь еще раз обработку ошибок - там еще остались паники в коде (в main и втором сторадже)

2022-03-19 12:03 UTC, merged